Try using the use-public-rspm option

diff --git a/.github/workflows/check-pak.yaml b/.github/workflows/check-pak.yaml
--- a/.github/workflows/check-pak.yaml
+++ b/.github/workflows/check-pak.yaml
@@ -28,7 +28,7 @@ jobs:
         config:
           #- {os: macOS-latest,   r: 'release'}
           #- {os: windows-latest, r: 'release'}
-          #- {os: windows-latest, r: '3.6', rspm: "https://packagemanager.rstudio.com/cran/latest"}
+          - {os: windows-latest, r: '3.6'}
           #- {os: ubuntu-18.04,   r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest", http-user-agent: "R/4.1.0 (ubuntu-18.04) R (4.1.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions" }
           - {os: ubuntu-18.04,   r: 'release'}
           #- {os: ubuntu-18.04,   r: 'oldrel',  rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
@@ -36,48 +36,49 @@ jobs:
           #- {os: ubuntu-18.04,   r: '3.5',     rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
           #- {os: ubuntu-18.04,   r: '3.4',     rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
 
-    env:
-      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
-
     steps:
       - uses: actions/checkout@v2
 
-      - uses: r-lib/actions/setup-r@v1
+      - uses: r-lib/actions/setup-r@use-public-rspm
         id: install-r
         with:
           r-version: ${{ matrix.config.r }}
           http-user-agent: ${{ matrix.config.http-user-agent }}
+          use-public-rspm: true
 
-      - uses: r-lib/actions/setup-pandoc@v1
-
-      - uses: r-lib/actions/setup-r-dependencies@needs
-        with:
-          needs: |
-            website
-            coverage
-          extra-packages: |
-            rcmdcheck
-            ggplot2
-
-      - run: echo $PATH
+      - run: cat ~/.Rprofile
         shell: bash
 
-      - name: Check
-        env:
-          _R_CHECK_CRAN_INCOMING_: false
-        run: |
-          options(crayon.enabled = TRUE)
-          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
-        shell: Rscript {0}
+      #- uses: r-lib/actions/setup-pandoc@v1
 
-      - name: Show testthat output
-        if: always()
-        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
+      #- uses: r-lib/actions/setup-r-dependencies@needs
+        #with:
+          #needs: |
+            #website
+            #coverage
+          #extra-packages: |
+            #rcmdcheck
+            #ggplot2
 
-      - name: Upload check results
-        if: failure()
-        uses: actions/upload-artifact@main
-        with:
-          name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-results
-          path: check
+      #- run: echo $PATH
+        #shell: bash
+
+      #- name: Check
+        #env:
+          #_R_CHECK_CRAN_INCOMING_: false
+        #run: |
+          #options(crayon.enabled = TRUE)
+          #rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
+        #shell: Rscript {0}
+
+      #- name: Show testthat output
+        #if: always()
+        #run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+        #shell: bash
+
+      #- name: Upload check results
+        #if: failure()
+        #uses: actions/upload-artifact@main
+        #with:
+          #name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-results
+          #path: check
